### PR TITLE
Trailing commas required on objects

### PR DESCRIPTION
**Pull request by ghost**
#123 If I understand correctly, this rule should solve your problem. I tried  this on my local machine and works well. It complete my objects with that last comma and warn an error when it is not in there.

👍 

*Edit:* I see on the travis build that now is requiring that missing comma dangle, it's this ok? that is are you waiting for?

### CODE REVIEW

**Comment by cale-bradbury** [comment]
Those look like good errors to have 😃 try running `yarn lint --fix` in the console to have it add the commas and fix those all up

**Comment by funwithtriangles** [comment]
I do love myself a bit of `comma-dangle`, thanks for this @Ranacode! A few things:

- As @netgrind has suggested, it's quite simple to fix those issues using `yarn lint --fix`
- What are your reasons for changing the spacing/formatting of this file? I feel it's less readable now
- Perhaps it might be best if we go for `comma-dangle: ["error", "always-multiline"]`?

**Comment by ghost** [comment]
Oops sorry, I forgot turn off my personal format in the editor, in respect of the "always-multiline" I think it's better than just "always" :).

Sorry for the format again, see you soon :)

**Comment by funwithtriangles** [comment]
We be danglin' from now on

**Pull request merged**
