### PR TITLE
finds sketches in subfolders of your sketch folder

### PR DESCRIPTION
**Pull request by cale-bradbury**

### CODE REVIEW

**Comment by cale-bradbury** [comment]
Seems to be an issue with fs not playing nicely with the `sinon` or `proxyquire`  in `sketches.spec.js`

**Comment by cale-bradbury** [comment]
Would love if you could check a look at the test file @funwithtriangles still new to unit tests and am wondering if I went about stubbing the fs in a good manner?

**Comment by funwithtriangles** [comment]
Thanks for this! I'll have a look tomorrow. Worth thinking about if there are a ton of folders, such as a rogue node_modules folder in there. Related bug: https://github.com/nudibranchrecords/hedron/issues/149

**Comment by cale-bradbury** [comment]
I think at the moment it doesn't look for subfolders if it finds an index and config, and node_modules would be a child of a folder with a index/config. I added a some node bits to a new sketch I'm working on and nothing seemed to explode

**Comment by funwithtriangles** [comment]
> node_modules would be a child of a folder with a index/config. 

Hmm I'm thinking more if `node_modules` is on the same level as all the other sketch folders. Thinking a simple check for "node_modules" directory name would be a safe way to stop it from diving forever!

**Comment by cale-bradbury** [comment]
I'll add an array of ignored folders with node_modules, perhaps in the future we could let a user add to this via settings

**Comment by cale-bradbury** [comment]
this is merged into #158

**Pull request closed without merging**
