### PR TITLE
Categorizes Sketches

### PR DESCRIPTION
**Pull request by cale-bradbury**
Adds `Revealers` to the `addSketch` window, organizes sketches based on a `category` tag in it's `config.js`
relates to #93

### CODE REVIEW

**Comment by cale-bradbury** [comment]
Feel like this is good for now, Going to work on adding different organization types down the line (author, folder), an after 0.5.0 thing

**Comment by funwithtriangles** [comment]
Thanks for this! I've made a few changes. Quick explanation:

- You didn't need to create new actions/reducer stuff for the opening and closing. There's `UI_AUX_TOGGLE_OPEN` which can be used for any random thing toggled open and closed, as long as you give the action a unique ID.
- To make things simpler, I've made an `AuxRevealer` container, where you just give the container component a unique `auxId` and it takes care of the rest. I've used `AuxRevealer` in the `AddSketch` component
- I've simplified `AddSketch` by moving most of the categorisation logic into a new selector, `getCategorizedModules`, so that the component can stay dumb
- `getCategorizedModules` is quite nice, it returns `looseItems` and `categorizedItems`, so when rendering the component we can have loose items up the top if the author has chosen not to use categories.

Let me know if that all makes sense! If that's all good I'll go ahead and merge. :)

**Comment by cale-bradbury** [comment]
I feel like there was a reason I didn't use UI_AUX_TOGGLE_OPEN, but I don't quite remember, maybe just reducing chance of clashing ids (since I was just using the category name). I'll check this out tonight, but I trust it's good!

**Comment by funwithtriangles** [comment]
Yeah I guess there is a slight namespace concern, but I've prefixed it with `sketchcat_` so I don't think it's too risky :)

**Comment by cale-bradbury** [comment]
I had merged the other pr into this one earlier, haha, oops, just going to close that one and this will merge them both :)

**Comment by funwithtriangles** [comment]
Just saw you were using `indexOf` instead of `includes` which is a bit neater for array checking.

In regards to your tests, they all look fine. I think if we were to be properly rigorous we'd think about how to test the recursive folder check but it's hurting my brain trying to think about how to mock that up with stubs so I'm just going to leave it for now!

Thanks again for this!

**Pull request merged**
