### PR TITLE
optional destructor function in sketch gets called upon deletion, use…

### PR DESCRIPTION
**Pull request by cale-bradbury**
…ful if there is anything that needs to be cleaned up

I use this for post effects, and a video player (adds a hidden video element to the dom in order to get a THREE.VideoTexture)

### CODE REVIEW

**Comment by funwithtriangles** [comment]
This looks good, nice idea. This is also a good example of why the docs need to be part of the source code, so changes like this can also come with some docs changes.

I'm sure it all works fine but I'm yet to test it my end, will try and find the time to do this weekend. I might write a little test for it too. :)

**Comment by cale-bradbury** [comment]
hmm, I couldn't really figure out how to do a pull request on the wiki :/
check my version here though, added a bit about how the scene gets passed into the constructor too!

edit: forgot link https://github.com/netgrind/hedron/wiki/Creating-Sketches

**Comment by netgrind** [comment]
I seemed to have not added the link

**Comment by funwithtriangles** [comment]
Merged, docs still need updating, captured in separate issue: https://github.com/nudibranchrecords/hedron/issues/45

**Pull request merged**
