### PR TITLE
Feature/audio increment

### PR DESCRIPTION
**Pull request by cale-bradbury**
Adds an increment option to audio modifiers, this is really good for rotation, or any other parameters that loop. causes the parameter value to continuously shift forward/backwards with the specified frequency band.

One issue is saved projects will be missing this new parameter, wondering what your thoughts are @funwithtriangles I remember at one point talking about possibly creating an upgrade function to funnel projects through, version to version

### CODE REVIEW

**Comment by funwithtriangles** [comment]
This is fantastic Cale! Have thought about this kind of feature before but never got round to implementing. Why not have it work for LFO too?

Just added my curent thoughts on backwards compatibility: https://github.com/nudibranchrecords/hedron/issues/184#issuecomment-477952552

**Comment by cale-bradbury** [comment]
Yeah, could add it to LFO as well, one thing that's a little tricky with this is that you often need super small numbers for the upper range, I suppose this is okay as you can type a value in though?

**Comment by funwithtriangles** [comment]
Hmm I guess that just depends on your sketch also? I don't see the harm in having it for LFO as well as audio, might be useful for someone!

**Comment by cale-bradbury** [comment]
I could imagine something pulsing forward in a sine motion feeling v nice ~~~

**Comment by funwithtriangles** [comment]
Moving any new pull requests to 0.6.0 apart from bugs, so 0.5.0 can get released

**Comment by funwithtriangles** [comment]
I converted this over to a modifier (had to rework modifiers a bit for this to work). The reasoning behind doing this is that eventually I'd like modifiers to be dropped in like sketches, so I want them to be flexible and allow for stuff like this increment feature. The API is a bit clunky for adding modifiers at the moment but I still think its neater to have them like this. :)

It also means that making this work for both audio and LFO is as simple as adding "LFO" to an array.

**Pull request merged**
