### PR TITLE
Added a simple noise functions to LFOs

### PR DESCRIPTION
**Pull request by esnho**
Added a noise LFO.
Due to the nature of how LFO functions are called two LFO with same rate returns the same noise value.

### CODE REVIEW

**Comment by esnho** [comment]
ci checks failed. sorry

**Comment by funwithtriangles** [comment]
Amazing! Been meaning to add a noise option. This is great, thanks! :)

No need to close a PR just cos some checks failed. The checks that have failed seem to be simple linting issues.  I can fix them, or you can. Let me know!

Look for "eslint" plugins for whatever editor. It should detect the style rules and show you what has gone wrong. Many editors have an option to "fix on save" for convenience. I got into the linting game late, absolutely love it now!

Also, this should fix a bunch of linting errors straight away: yarn lint:fix

**Comment by esnho** [comment]
> Amazing! Been meaning to add a noise option. This is great, thanks! :)

Thank you. This project is great! :)

I'm using Atom, I will test linter soon, thanks for the advice.
I still have problem running tests on my windows machine, trying to figure out.

Just pushed the lint fixes, now should be ok.

**Comment by funwithtriangles** [comment]
Nice one. I'll make sure to find a time to properly review this at the weekend. :)

**Comment by funwithtriangles** [comment]
This is brilliant! Thanks again! 🕺

**Comment by esnho** [comment]
Thank you for hedron! 😃

**Pull request merged**
